# Generated by Django 5.2.1 on 2025-05-30 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_customuser_managers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="carehome",
            name="day_shift_start",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
