# Generated by Django 5.2.1 on 2025-05-30 20:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_carehome_day_shift_start"),
    ]

    operations = [
        migrations.CreateModel(
            name="ABCForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_user", models.CharField(max_length=255)),
                ("date_of_birth", models.DateField()),
                ("staff", models.CharField(max_length=255)),
                ("behaviour_started", models.DateTimeField()),
                ("setting", models.TextField()),
                ("antecedent", models.TextField()),
                ("behaviour", models.TextField()),
                ("consequences", models.TextField()),
                ("reflection", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="IncidentReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("incident_datetime", models.DateTimeField()),
                ("location", models.CharField(max_length=255)),
                ("service_user", models.CharField(max_length=255)),
                ("dob", models.DateField()),
                ("staff_involved", models.CharField(max_length=255)),
                ("prior_description", models.TextField()),
                ("incident_description", models.TextField()),
                ("user_response", models.TextField()),
                ("contacted_manager", models.BooleanField(default=False)),
                ("contacted_police", models.BooleanField(default=False)),
                ("contacted_paramedics", models.BooleanField(default=False)),
                ("injuries_detail", models.TextField(blank=True)),
                ("property_damage", models.TextField(blank=True)),
                ("prn_administered", models.BooleanField(default=False)),
                ("prn_by_whom", models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
