# Generated by Django 5.2.1 on 2025-05-30 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_abcform_incidentreport"),
    ]

    operations = [
        migrations.CreateModel(
            name="LogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shift", models.CharField(max_length=50)),
                ("date", models.DateField(auto_now_add=True)),
                ("time_slot", models.TimeField()),
                ("content", models.TextField(blank=True)),
                ("is_locked", models.BooleanField(default=False)),
                (
                    "carehome",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.carehome"
                    ),
                ),
                (
                    "service_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.serviceuser",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_log_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
