# Generated by Django 5.2.1 on 2025-06-01 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_logentry"),
    ]

    operations = [
        migrations.CreateModel(
            name="LatestLogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shift", models.CharField(max_length=50)),
                ("date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[("incomplete", "Incomplete"), ("locked", "Locked")],
                        max_length=20,
                    ),
                ),
                (
                    "log_pdf",
                    models.FileField(blank=True, null=True, upload_to="log_pdfs/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "carehome",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.carehome"
                    ),
                ),
                (
                    "service_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.serviceuser",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
