# Generated by Django 5.2.1 on 2025-06-02 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_latestlogentry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incidentreport",
            name="service_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.serviceuser"
            ),
        ),
    ]
