# Generated by Django 5.2.1 on 2025-06-07 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_alter_incidentreport_service_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="incidentreport",
            name="carehome",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.carehome",
            ),
        ),
        migrations.AddField(
            model_name="incidentreport",
            name="pdf_file",
            field=models.FileField(
                blank=True, null=True, upload_to="incident_reports/"
            ),
        ),
        migrations.AddField(
            model_name="incidentreport",
            name="staff",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("manager", "Manager"),
                    ("staff", "Staff"),
                    ("team_lead", "Team Lead"),
                ],
                default="staff",
                max_length=20,
            ),
        ),
    ]
