# Generated by Django 5.2.1 on 2025-06-07 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_incidentreport_carehome_incidentreport_pdf_file_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("carehomes", models.ManyToManyField(to="core.carehome")),
                ("service_users", models.ManyToManyField(to="core.serviceuser")),
                (
                    "staff",
                    models.ForeignKey(
                        limit_choices_to={"role": "staff"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
