# Generated by Django 5.2.1 on 2025-06-18 07:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_mapping"),
    ]

    operations = [
        migrations.AddField(
            model_name="abcform",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="abcform",
            name="pdf_file",
            field=models.FileField(blank=True, null=True, upload_to="abc_pdfs/"),
        ),
        migrations.AlterField(
            model_name="abcform",
            name="service_user",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="abcform",
            name="staff",
            field=models.CharField(max_length=100),
        ),
    ]
