# Generated by Django 5.2.1 on 2025-06-18 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_abcform_created_at_abcform_pdf_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="abcform",
            name="service_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.serviceuser"
            ),
        ),
    ]
