# Generated by Django 5.2.1 on 2025-06-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_alter_abcform_service_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="carehome",
            old_name="day_shift_start",
            new_name="morning_shift_start",
        ),
        migrations.AddField(
            model_name="carehome",
            name="night_shift_start",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
