# Generated by Django 5.2.1 on 2025-06-24 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_rename_day_shift_start_carehome_morning_shift_start_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="logentry",
            name="latest_log",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.latestlogentry",
            ),
        ),
    ]
