# Generated by Django 5.2.1 on 2025-06-27 10:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_logentry_latest_log"),
    ]

    operations = []
