# Generated by Django 5.2.1 on 2025-06-27 10:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_populate_date_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="abcform",
            name="behaviour_started",
        ),
        migrations.AddField(
            model_name="abcform",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_abc_forms",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Form Creator",
            ),
        ),
        migrations.AddField(
            model_name="abcform",
            name="date_time",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                verbose_name="DATE/TIME Behavior started",
            ),
        ),
        migrations.AddField(
            model_name="abcform",
            name="target_behaviours",
            field=models.JSONField(
                default=list, help_text="List of selected target behaviours"
            ),
        ),
        migrations.AddField(
            model_name="abcform",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="abcform",
            name="antecedent",
            field=models.TextField(verbose_name="ANTECEDENT"),
        ),
        migrations.AlterField(
            model_name="abcform",
            name="behaviour",
            field=models.TextField(verbose_name="BEHAVIOUR"),
        ),
        migrations.AlterField(
            model_name="abcform",
            name="consequences",
            field=models.TextField(verbose_name="CONSEQUENCES"),
        ),
        migrations.AlterField(
            model_name="abcform",
            name="reflection",
            field=models.TextField(verbose_name="REFLECTION"),
        ),
        migrations.AlterField(
            model_name="abcform",
            name="service_user",
            field=models.CharField(max_length=100, verbose_name="Service User"),
        ),
        migrations.AlterField(
            model_name="abcform",
            name="setting",
            field=models.TextField(verbose_name="SETTING"),
        ),
        migrations.AlterField(
            model_name="abcform",
            name="staff",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staff_abc_forms",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Staff Member",
            ),
        ),
    ]
