# Generated by Django 5.2.1 on 2025-06-27 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_remove_abcform_behaviour_started_abcform_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="abcform",
            name="service_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="abc_forms",
                to="core.serviceuser",
                verbose_name="Service User",
            ),
        ),
    ]
