# Generated by Django 5.2.1 on 2025-06-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_alter_abcform_service_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="abcform",
            name="staff",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
