# Generated by Django 5.2.1 on 2025-07-04 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_alter_abcform_staff"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="latestlogentry",
            options={
                "ordering": ["-date", "-created_at"],
                "verbose_name_plural": "Latest Log Entries",
            },
        ),
        migrations.AlterModelOptions(
            name="logentry",
            options={
                "ordering": ["date", "time_slot"],
                "verbose_name_plural": "Log Entries",
            },
        ),
        migrations.AddField(
            model_name="latestlogentry",
            name="day_of_week",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="abcform",
            name="antecedent",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="abcform",
            name="behaviour",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="abcform",
            name="consequences",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="abcform",
            name="reflection",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="abcform",
            name="setting",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="latestlogentry",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="latestlogentry",
            name="status",
            field=models.CharField(
                choices=[("incomplete", "Incomplete"), ("locked", "Locked")],
                default="incomplete",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="logentry",
            name="latest_log",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="log_entries",
                to="core.latestlogentry",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="latestlogentry",
            unique_together={("user", "service_user", "date", "shift")},
        ),
    ]
