# Generated by Django 5.2.1 on 2025-07-04 20:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_alter_latestlogentry_options_alter_logentry_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="latestlogentry",
            name="staff_name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
