# Generated by Django 5.2.1 on 2025-07-04 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_latestlogentry_staff_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="latestlogentry",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="latestlogentry",
            name="carehome",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="latest_log_entries",
                to="core.carehome",
            ),
        ),
        migrations.AlterField(
            model_name="latestlogentry",
            name="service_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="latest_log_entries",
                to="core.serviceuser",
            ),
        ),
        migrations.AlterField(
            model_name="latestlogentry",
            name="shift",
            field=models.CharField(
                choices=[
                    ("morning", "Morning"),
                    ("afternoon", "Afternoon"),
                    ("night", "Night"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="latestlogentry",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="latest_log_entries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="latestlogentry",
            index=models.Index(
                fields=["user", "date"], name="core_latest_user_id_2fa1fe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="latestlogentry",
            index=models.Index(
                fields=["carehome", "date"], name="core_latest_carehom_dfab73_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="latestlogentry",
            index=models.Index(
                fields=["service_user", "date"], name="core_latest_service_dabdb4_idx"
            ),
        ),
    ]
