# Generated by Django 5.2.1 on 2025-07-05 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_latestlogentry_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="carehome",
            name="morning_shift_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="carehome",
            name="night_shift_end",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
