# Generated by Django 5.2.1 on 2025-07-07 16:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0021_carehome_morning_shift_end_carehome_night_shift_end"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="incidentreport",
            name="pdf_file",
        ),
        migrations.AddField(
            model_name="incidentreport",
            name="contacted_other",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="incidentreport",
            name="manager_contact_comment",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="incidentreport",
            name="manager_contact_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="incidentreport",
            name="other_contact_comment",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="incidentreport",
            name="other_contact_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="incidentreport",
            name="other_contact_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="incidentreport",
            name="paramedics_contact_comment",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="incidentreport",
            name="paramedics_contact_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="incidentreport",
            name="police_contact_comment",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="incidentreport",
            name="police_contact_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
