# Generated by Django 5.2.1 on 2025-07-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0022_remove_incidentreport_pdf_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="incidentreport",
            name="pdf_file",
            field=models.FileField(
                blank=True, null=True, upload_to="incident_reports/"
            ),
        ),
    ]
