# Generated by Django 5.2.1 on 2025-07-09 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0023_incidentreport_pdf_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="incidentreport",
            name="image1",
            field=models.ImageField(
                blank=True, null=True, upload_to="incident_images/"
            ),
        ),
        migrations.AddField(
            model_name="incidentreport",
            name="image2",
            field=models.ImageField(
                blank=True, null=True, upload_to="incident_images/"
            ),
        ),
        migrations.AddField(
            model_name="incidentreport",
            name="image3",
            field=models.ImageField(
                blank=True, null=True, upload_to="incident_images/"
            ),
        ),
    ]
