# Generated by Django 5.2.1 on 2025-07-18 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_incidentreport_image1_incidentreport_image2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="carehome",
            name="managers",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"role__in": ["manager", "team_lead"]},
                related_name="managed_carehomes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="serviceuser",
            name="carehome",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_users",
                to="core.carehome",
            ),
        ),
    ]
