# Generated by Django 5.2.1 on 2025-07-22 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0025_carehome_managers_alter_serviceuser_carehome"),
    ]

    operations = [
        migrations.AddField(
            model_name="abcform",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_abc_forms",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Last Updated By",
            ),
        ),
    ]
