# Generated by Django 5.2.1 on 2025-07-26 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0026_abcform_updated_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="MissedLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "shift",
                    models.CharField(
                        choices=[("morning", "Morning"), ("afternoon", "Afternoon")],
                        max_length=20,
                    ),
                ),
                ("is_notified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "carehome",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="missed_logs",
                        to="core.carehome",
                    ),
                ),
                (
                    "service_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="missed_logs",
                        to="core.serviceuser",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Missed Logs",
                "ordering": ["-date", "shift"],
                "unique_together": {("service_user", "date", "shift")},
            },
        ),
    ]
