# Generated by Django 5.2.1 on 2025-07-26 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0027_missedlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="latestlogentry",
            name="shift",
            field=models.CharField(
                choices=[("morning", "Morning"), ("night", "Night")], max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="missedlog",
            name="shift",
            field=models.CharField(
                choices=[("morning", "Morning"), ("night_shift", "Night Shift")],
                max_length=20,
            ),
        ),
    ]
