# Generated by Django 5.2.1 on 2025-07-26 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0028_alter_latestlogentry_shift_alter_missedlog_shift"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="missedlog",
            options={
                "ordering": ["-date", "carehome", "shift"],
                "verbose_name": "Missed Shift",
                "verbose_name_plural": "Missed Shifts",
            },
        ),
        migrations.AlterUniqueTogether(
            name="missedlog",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="missedlog",
            name="carehome",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.carehome"
            ),
        ),
        migrations.AlterField(
            model_name="missedlog",
            name="service_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.serviceuser"
            ),
        ),
        migrations.AlterField(
            model_name="missedlog",
            name="shift",
            field=models.CharField(
                choices=[("morning", "Morning"), ("night", "Night")], max_length=20
            ),
        ),
        migrations.AddIndex(
            model_name="missedlog",
            index=models.Index(fields=["-date"], name="core_missed_date_4a77cd_idx"),
        ),
        migrations.AddIndex(
            model_name="missedlog",
            index=models.Index(
                fields=["carehome"], name="core_missed_carehom_8b4b2f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="missedlog",
            index=models.Index(fields=["shift"], name="core_missed_shift_4d21f9_idx"),
        ),
    ]
