# Generated by Django 5.2.1 on 2025-07-26 11:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0029_alter_missedlog_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="missedlog",
            options={
                "verbose_name": "Missed Shift",
                "verbose_name_plural": "Missed Shifts",
            },
        ),
        migrations.RemoveIndex(
            model_name="missedlog",
            name="core_missed_date_4a77cd_idx",
        ),
        migrations.RemoveIndex(
            model_name="missedlog",
            name="core_missed_carehom_8b4b2f_idx",
        ),
        migrations.RemoveIndex(
            model_name="missedlog",
            name="core_missed_shift_4d21f9_idx",
        ),
    ]
